print("SYÖHENKILÖN TIEDOT")
print("-------------------")

etunimi = input("Anna etunimet: ")
sukunimi = input("Anna sukunimi: ")
puhelin = input("Anna puhelinnumero: ")
sposti = input("Anna sähköpostiosoite: ")
osoite = input("Anna lähiosoite: ")
posti = input("Anna postinumero: ")
kaupunki = input("Anna kaupunki: ")
maa = input("Anna maa: ")
vuosi = int(input("Anna syntymävuosi: "))

print("KIITOS!")

print("HENKILÖN TIEDOT")
print("----------------")

print("NIMI:")
print(f"{sukunimi}, {etunimi}")
print("PUH:")
print(f"{puhelin}")
print("EMAIL:")
print(f"{sposti}")
print("OSOITE: ")
print(osoite)
print(posti+" "+kaupunki)
print(maa)
print(f"ikä:  {2023 - vuosi}")

